name = "y12m"
maintainer = ["@ivan-pi"]
author = ["Zahari Zlatev"]
homepage = "http://www.netlib.org/y12m/"
keywords = ["sparse", "linear", "algebra", "direct", "method"]
description = "Solution of Large and Sparse Systems of Linear Algebraic Equations"

[library]
source-dir = "src"

[build]
auto-tests = false