# CMake generated Testfile for 
# Source directory: /home/runner/work/y12m/y12m/test
# Build directory: /home/runner/work/y12m/y12m/build2/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_y12ma_sp "/home/runner/work/y12m/y12m/build2/test/test_y12ma_sp")
set_tests_properties(test_y12ma_sp PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/y12m/y12m/test/CMakeLists.txt;20;add_test;/home/runner/work/y12m/y12m/test/CMakeLists.txt;0;")
add_test(test_y12ma_dp "/home/runner/work/y12m/y12m/build2/test/test_y12ma_dp")
set_tests_properties(test_y12ma_dp PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/y12m/y12m/test/CMakeLists.txt;20;add_test;/home/runner/work/y12m/y12m/test/CMakeLists.txt;0;")
add_test(test_y12mb_mc_md_sp "/home/runner/work/y12m/y12m/build2/test/test_y12mb_mc_md_sp")
set_tests_properties(test_y12mb_mc_md_sp PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/y12m/y12m/test/CMakeLists.txt;20;add_test;/home/runner/work/y12m/y12m/test/CMakeLists.txt;0;")
add_test(test_y12mb_mc_md_dp "/home/runner/work/y12m/y12m/build2/test/test_y12mb_mc_md_dp")
set_tests_properties(test_y12mb_mc_md_dp PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/y12m/y12m/test/CMakeLists.txt;20;add_test;/home/runner/work/y12m/y12m/test/CMakeLists.txt;0;")
add_test(test_y12mf_sp "/home/runner/work/y12m/y12m/build2/test/test_y12mf_sp")
set_tests_properties(test_y12mf_sp PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/y12m/y12m/test/CMakeLists.txt;20;add_test;/home/runner/work/y12m/y12m/test/CMakeLists.txt;0;")
add_test(test_y12mf_errors "/home/runner/work/y12m/y12m/build2/test/test_y12mf_errors")
set_tests_properties(test_y12mf_errors PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/y12m/y12m/test/CMakeLists.txt;20;add_test;/home/runner/work/y12m/y12m/test/CMakeLists.txt;0;")
add_test(test_y12mg_mh "/home/runner/work/y12m/y12m/build2/test/test_y12mg_mh")
set_tests_properties(test_y12mg_mh PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/y12m/y12m/test/CMakeLists.txt;20;add_test;/home/runner/work/y12m/y12m/test/CMakeLists.txt;0;")
add_test(test_y12ma_y12mf_bench_sp "/home/runner/work/y12m/y12m/build2/test/test_y12ma_y12mf_bench_sp")
set_tests_properties(test_y12ma_y12mf_bench_sp PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/y12m/y12m/test/CMakeLists.txt;20;add_test;/home/runner/work/y12m/y12m/test/CMakeLists.txt;0;")
add_test(test_y12ma_5x5_sp "/home/runner/work/y12m/y12m/build2/test/test_y12ma_5x5_sp")
set_tests_properties(test_y12ma_5x5_sp PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/y12m/y12m/test/CMakeLists.txt;34;add_test;/home/runner/work/y12m/y12m/test/CMakeLists.txt;0;")
add_test(test_y12ma_5x5_dp "/home/runner/work/y12m/y12m/build2/test/test_y12ma_5x5_dp")
set_tests_properties(test_y12ma_5x5_dp PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/y12m/y12m/test/CMakeLists.txt;34;add_test;/home/runner/work/y12m/y12m/test/CMakeLists.txt;0;")
add_test(test_y12mb_errors_sp "/home/runner/work/y12m/y12m/build2/test/test_y12mb_errors_sp")
set_tests_properties(test_y12mb_errors_sp PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/y12m/y12m/test/CMakeLists.txt;49;add_test;/home/runner/work/y12m/y12m/test/CMakeLists.txt;0;")
add_test(test_y12mb_errors_dp "/home/runner/work/y12m/y12m/build2/test/test_y12mb_errors_dp")
set_tests_properties(test_y12mb_errors_dp PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/y12m/y12m/test/CMakeLists.txt;49;add_test;/home/runner/work/y12m/y12m/test/CMakeLists.txt;0;")
add_test(test_y12mc_errors_sp "/home/runner/work/y12m/y12m/build2/test/test_y12mc_errors_sp")
set_tests_properties(test_y12mc_errors_sp PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/y12m/y12m/test/CMakeLists.txt;63;add_test;/home/runner/work/y12m/y12m/test/CMakeLists.txt;0;")
add_test(test_y12mc_errors_dp "/home/runner/work/y12m/y12m/build2/test/test_y12mc_errors_dp")
set_tests_properties(test_y12mc_errors_dp PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/y12m/y12m/test/CMakeLists.txt;63;add_test;/home/runner/work/y12m/y12m/test/CMakeLists.txt;0;")
add_test(test_y12md_errors_sp "/home/runner/work/y12m/y12m/build2/test/test_y12md_errors_sp")
set_tests_properties(test_y12md_errors_sp PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/y12m/y12m/test/CMakeLists.txt;77;add_test;/home/runner/work/y12m/y12m/test/CMakeLists.txt;0;")
add_test(test_y12md_errors_dp "/home/runner/work/y12m/y12m/build2/test/test_y12md_errors_dp")
set_tests_properties(test_y12md_errors_dp PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/y12m/y12m/test/CMakeLists.txt;77;add_test;/home/runner/work/y12m/y12m/test/CMakeLists.txt;0;")
add_test(test_y12mc_z_intent_sp "/home/runner/work/y12m/y12m/build2/test/test_y12mc_z_intent_sp")
set_tests_properties(test_y12mc_z_intent_sp PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/y12m/y12m/test/CMakeLists.txt;91;add_test;/home/runner/work/y12m/y12m/test/CMakeLists.txt;0;")
add_test(test_y12mc_z_intent_dp "/home/runner/work/y12m/y12m/build2/test/test_y12mc_z_intent_dp")
set_tests_properties(test_y12mc_z_intent_dp PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/y12m/y12m/test/CMakeLists.txt;91;add_test;/home/runner/work/y12m/y12m/test/CMakeLists.txt;0;")
add_test(y12m_solve_mat0 "/home/runner/work/y12m/y12m/build2/test/y12m_solve" "--verbose" "/home/runner/work/y12m/y12m/test/data/mat0.mtx")
set_tests_properties(y12m_solve_mat0 PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/y12m/y12m/test/CMakeLists.txt;106;add_test;/home/runner/work/y12m/y12m/test/CMakeLists.txt;0;")
add_test(y12m_solve_mat1 "/home/runner/work/y12m/y12m/build2/test/y12m_solve" "--verbose" "/home/runner/work/y12m/y12m/test/data/mat1.mtx")
set_tests_properties(y12m_solve_mat1 PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/y12m/y12m/test/CMakeLists.txt;106;add_test;/home/runner/work/y12m/y12m/test/CMakeLists.txt;0;")
add_test(y12m_solve_mat2 "/home/runner/work/y12m/y12m/build2/test/y12m_solve" "--verbose" "/home/runner/work/y12m/y12m/test/data/mat2.mtx")
set_tests_properties(y12m_solve_mat2 PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/y12m/y12m/test/CMakeLists.txt;106;add_test;/home/runner/work/y12m/y12m/test/CMakeLists.txt;0;")
add_test(y12m_solve_mat3 "/home/runner/work/y12m/y12m/build2/test/y12m_solve" "--verbose" "/home/runner/work/y12m/y12m/test/data/mat3.mtx")
set_tests_properties(y12m_solve_mat3 PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/y12m/y12m/test/CMakeLists.txt;106;add_test;/home/runner/work/y12m/y12m/test/CMakeLists.txt;0;")
add_test(y12m_solve_mat5 "/home/runner/work/y12m/y12m/build2/test/y12m_solve" "--verbose" "/home/runner/work/y12m/y12m/test/data/mat5.mtx")
set_tests_properties(y12m_solve_mat5 PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/y12m/y12m/test/CMakeLists.txt;106;add_test;/home/runner/work/y12m/y12m/test/CMakeLists.txt;0;")
